name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Last Tag
        id: last_tag
        run: |
          latest=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")

          echo "last_tag=$latest" >> $GITHUB_ENV

      - name: Get Release Notes
        id: release_notes
        run: |
          last_tag=${{ env.last_tag }}

          if [ "$last_tag" = "v0.0.0" ]; then
            commits=$(git log --pretty=format:"- %s")
          else
            commits=$(git log "$last_tag"..HEAD --pretty=format:"- %s")
          fi

          escaped_commits=$(printf "%s" "$commits" | jq -Rsa .)

          echo "release_notes=$escaped_commits" >> $GITHUB_ENV

      - name: Generate Next Version Tag
        id: versioning
        run: |
          release_notes=${{ env.release_notes }}

          hasMajor=0
          hasMinor=0
          hasPatch=0


          while IFS= read -r line; do
            echo "Processing line: $line" # Debugging: Print each line

            if [[ $line == *BREAKING* ]]; then
              hasMajor=1
            elif [[ $line == feat:* ]]; then
              hasMinor=1
            elif [[ $line == fix:* ]]; then
              hasPatch=1
            fi
          done <<< "$release_notes"

          echo "$hasMajor"
          echo "$hasMinor"
          echo "$hasPatch"

          last_tag=${{ env.last_tag }}

          major=$(echo $last_tag | awk -F. '{print $1}' | tr -d 'v')
          minor=$(echo $last_tag | awk -F. '{print $2}')
          patch=$(echo $last_tag | awk -F. '{print $3}')

          next_patch=$((patch + 1))

          next_version="v${major}.${minor}.${next_patch}"

          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -a ${{ env.next_version }} -m "Release version ${{ env.next_version }}"
          git push origin ${{ env.next_version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.next_version }}
          release_name: "Release ${{ env.next_version }}"
          body: ${{ fromJSON(env.release_notes) }}
          draft: false
          prerelease: false
